---
sidebar: sidebar 
permalink: reference-new.html 
keywords: new features, release notes, enhancements 
summary: Cloud Volumes ONTAP 9.11.0 inclut une nouvelle amélioration. 
---
= Nouveautés de Cloud Volumes ONTAP 9.11.0
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Cloud Volumes ONTAP 9.11.0 inclut une nouvelle amélioration.

D'autres fonctionnalités et améliorations sont également introduites dans les dernières versions de Cloud Manager. Voir la https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/whats-new.html["Notes de version de Cloud Manager"^] pour plus d'informations.



== Les instances c4, m4 et r4 ne sont plus prises en charge (28 octobre 2022)

Dans AWS, les types d'instances EC2 c4, m4 et r4 ne sont plus pris en charge par Cloud Volumes ONTAP. Si un système existant s'exécute sur un type d'instance c4, m4 ou r4, vous devez passer à un type d'instance dans la famille d'instances c5, m5 ou r5.

link:https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/task-change-ec2-instance.html["Découvrez comment modifier le type d'instance EC2 pour Cloud Volumes ONTAP"^].

Reportez-vous à la section link:https://mysupport.netapp.com/info/communications/ECMLP2880231.html["Support NetApp"^] pour en savoir plus sur la fin de disponibilité et la prise en charge de ces types d'instances.



== Prise en charge d'Elastic volumes (7 juin 2022)

La prise en charge d'Amazon EBS Elastic volumes via un agrégat Cloud Volumes ONTAP améliore les performances et la capacité, tout en permettant à Cloud Manager d'augmenter automatiquement la capacité sous-jacente du disque selon les besoins.

La prise en charge des volumes Elastic est disponible à partir de la version 3.9.19 du connecteur Cloud Manager et est prise en charge avec les versions Cloud Volumes ONTAP spécifiques et les types de disques EBS spécifiques.

https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/concept-aws-elastic-volumes.html["En savoir plus sur la prise en charge d'Elastic volumes"^]



== 9.11.0 P1 (2 mai 2022)

La version Cloud Volumes ONTAP 9.11.0 P1 est désormais disponible dans AWS, Azure et Google Cloud. Cette version comprend les améliorations suivantes.



=== Prise en charge d'ONTAP S3 dans AWS

Vous pouvez désormais fournir un stockage objet S3 à partir d'Cloud Volumes ONTAP dans AWS (Microsoft Azure est déjà pris en charge). Cloud Volumes ONTAP prend en charge S3 en tant qu'option pour le stockage scale-out, en plus des protocoles classiques basés sur des fichiers tels que NFS et SMB.

Notez ce qui suit :

* L'utilisation principale d'ONTAP S3 avec Cloud Volumes ONTAP est un magasin d'objets à usage générique.
* Pour l'instant, le protocole S3 n'est pas pris en charge par Cloud Volumes ONTAP dans Google Cloud.
* Cloud Manager ne fournit aucune fonctionnalité de gestion pour la fonctionnalité ONTAP S3.


https://docs.netapp.com/us-en/ontap/object-storage-management/index.html["Découvrez comment configurer et gérer les services de stockage objet S3 dans ONTAP"^].



== Notes de mise à niveau

Lisez ces notes pour en savoir plus sur la mise à niveau vers cette version.



=== Comment mettre à niveau

La mise à niveau d'Cloud Volumes ONTAP doit être effectuée depuis Cloud Manager. Vous ne devez pas mettre à niveau Cloud Volumes ONTAP à l'aide de System Manager ou de l'interface de ligne de commandes. Cela peut affecter la stabilité du système.

http://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/task-updating-ontap-cloud.html["Découvrez comment effectuer la mise à niveau lorsque Cloud Manager vous informe"^].



=== Chemin de mise à niveau pris en charge

Vous pouvez effectuer la mise à niveau vers Cloud Volumes ONTAP 9.11.0 à partir de la version 9.10.1. Cloud Manager vous invite à mettre à niveau les systèmes Cloud Volumes ONTAP éligibles vers cette version.



=== Version requise du connecteur

Cloud Manager Connector doit exécuter la version 3.9.18 ou ultérieure pour mettre à niveau les systèmes existants vers la version 9.11.0.


TIP: Les mises à niveau automatiques du connecteur sont activées par défaut, vous devez donc exécuter la dernière version.



=== Ou non

* La mise à niveau d'un système à un nœud unique permet de mettre le système hors ligne pendant 25 minutes au cours desquelles les E/S sont interrompues.
* La mise à niveau d'une paire haute disponibilité s'effectue sans interruption et les E/S sont continues. Au cours de ce processus de mise à niveau sans interruption, chaque nœud est mis à niveau en tandem afin de continuer à traiter les E/S aux clients.

